import 'package:get/get_navigation/src/root/internacionalization.dart';

class TextConst extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {

          'sentOTPforsignup': 'Sent OTP for Signup',
          'enteryourphonenumbertogetyourotp': 'Enter your phone number to get your OTP',


          'mobileView': 'Mobile View',
          'tabletView': 'Tablet View',
          'desktopView': 'Desktop View',
          'mmhf': 'MMHF',
          'easyDigital': 'Easy digital toll pass',
          'welcomeScreenDetails': 'Experience seamless road trips with our Easy Digital Toll Pass. No queues, no cash – just smooth sailing',
          'welcome': 'Welcome!',
          'pleasePutYourDetails': 'Please input your details to continue',
          'phoneNumber': 'Phone number',
          'enterYourNumber': 'Enter your number',
          'pleaseEnterValidNumber': 'Please enter a valid phone number',
          'login': 'Login with otp',
          'dontHaveanAccount': "Don't have an account?",
          'signup': 'Sign up',
          'orSignIn': 'or sign in with',
          'enterVerifyCode': 'Enter Verify Code',
          'sentCodeInfo': 'We sent a verification code to the number',
          'next': 'Next',
          'resendCode': 'Resend code',
          'availableTollPass': 'Your available toll pass',
          'buyTripPass': 'Buy Trip Pass',
          'home': 'Home',
          'usageHistory': 'Usage History',
          'account': 'Account',
          'more': 'More',
          'myAccount': 'My Account',
          'addVehicle': 'Add vehicle',
          'transactionUsagehistory': 'Transaction & Usages history',
          'myVehicles': 'My Vehicles',
          'qRCollectionPoint': 'QR Collection Point',
          'support': 'Support',
          'gallery': 'Gallery',
          'about': 'About Us',
          'termsConditions': 'Terms & conditions',
          'privacyPolicy': 'Privacy Policy',
          'logout': 'Log out',
          'buildingNumber': 'Building Number :',
          'streetName': 'Street Name :',
          'streetAddress': 'Street Address :',
          'state': 'State :',
          'city': 'City :',
          'postCode': 'Post Code :',
          'qRCodeCollectionPoint': 'QR Collection Point',
          'contactUS': 'Contact us',
          'callingUS': 'If you are facing any issues, please contact us by calling ',
          'orEmailing': ' (8am-10pm) or emailing us at ',
          'createSupport': 'Create Support',
          'supportHistory': 'Support History',
          'selectIssue': 'Select issue',
          'explainYourIssue': 'Please explain your issue',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',
          '': '',

        }
      };
}
